name: Deploy
on: workflow_dispatch
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-20.04
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - run: yarn install

      - run: yarn build
      - uses: aws-actions/configure-aws-credentials@v3.0.1
        with:
          role-to-assume: ${{ vars.IAM_ROLE_ARN }}
          aws-region: us-east-1
      - name: Upload static content
        run: aws s3 sync build s3://${{ vars.S3_BUCKET }}/ --no-progress --follow-symlinks --delete
